---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_PUBLISH_BACKEND_WWW####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result
      
    - name: publish www
      shell: dotnet publish --no-self-contained -r linux-musl-x64 --configuration Release -o www /home/awx/orion/backend/Orion/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_BACKEND####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/backend:{{ ORION_ARCH }}-latest /home/awx/orion/backend/Orion/www >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_BACKEND####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'backend'
      shell: docker images --filter reference=dbmorion/backend  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result