---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Enviar script Docker Buildx
      copy:
        content: |
          #!/bin/bash
          docker buildx build --no-cache --platform ${{ ORION_ARCH }} -t ${{ ORION_REGISTRY }}/files:${{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/files

        dest: /home/awx/orion/infra/servicos/files/docker_build_script.sh
        mode: '0755'

    - name: Executar script Docker Buildx
      shell: cd /home/awx/orion/infra/servicos/files/ && ./docker_build_script.sh

    - name: Executar 'docker images' para listar imagens com 'files'
      command: docker images --filter "reference=*files*" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result
