- name: Criar diretórios e definir permissões
  become: yes
  hosts: "{{ host_awx }}"
  gather_facts: no
  tasks:

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
    
    - name: Criar imagem docker files
      patch: /home/awx/orion/infra/servicos/files
      shell: docker build --no-cache --force-rm -t ${ORION_REGISTRY}/files:${ORION_ARCH}-latest .
      
    - name: Executar 'docker images'
      shell: docker images --filter "reference=*files*"  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1  

      



