---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Acessar path files
      shell: cd /home/awx/orion/infra/servicos/files
      args:
        executable: /bin/bash  # Especifique o shell a ser usado (neste caso, /bin/bash).

    - name: Enviar script Docker Buildx
      copy:
        content: |
          #!/bin/bash
          docker buildx build --no-cache --progress plain --platform ${ORION_ARCH} -t ${ORION_REGISTRY}/files:${ORION_ARCH}-latest .
        dest: /tmp/docker_build_script.sh
        mode: '0755'
      become: yes

    - name: Executar script Docker Buildx
      command: /tmp/docker_build_script.sh
      ignore_errors: yes
      become: yes
