---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Criar arquivo
      file:
        path: /var/volumes/gateway/includes/dundi_peers.conf
        state: touch

    # Adiciona o texto ao arquivo
    - name: Adicionar texto
      lineinfile:
        path: /var/volumes/gateway/includes/dundi_peers.conf
        line: |
          [52:54:00:28:3f:be];
          model = symmetric
          precache = none
          host = 10.211.55.28;
          port = 4520
          inkey = dundi
          outkey = dundi
          include = dundi_context
          permit = dundi_context
          qualify = 6500
          register = no
        insertafter: "# Cria um arquivo chamado 'node02.conf'"  