- name: Criar diretórios e definir permissões
  become: yes
  hosts: "{{ host_awx }}"
  gather_facts: no
  tasks:
    - name: Criar diretórios usando o módulo file
      file:
        path: /var/volumes
        state: directory
        mode: "0775"  # Define as permissões para 775 (rwxrwxr-x)
      ignore_errors: yes

    - name: Criar diretórios dentro de /var/volumes
      file:
        path: "/var/volumes/{{ item }}"
        state: directory
        mode: "0775"
      loop:
        - backend/logs
        - rabbitmq/logs
        - bd/logs
        - frontend/conf.d
        - gateway/includes
        - gateway/logs
        - worker/logs
        - gateway/logs/cdr-csv
        - gateway/logs/cdr-custom
        - loadbalancer/includes
        - voice/logs
        - voice/logs/cdr-csv
        - voice/logs/cdr-custom
      ignore_errors: yes



