- name: Adicionar variáveis ao ~/.bashrc
  hosts: "{{ host_awx }}"
  gather_facts: no
  tasks:
    - name: Adicionar variáveis ao ~/.bashrc
      lineinfile:
        dest: ~/.bashrc
        line: "{{ item }}"
      loop:
        - 'export ORION_ARCH=amd64'
        - 'export ORION_REGISTRY=dbmorion'
        - 'export ORION_ENTRYPOINT={{ host_awx }}'
        - 'export ASPNETCORE_ENVIRONMENT={{ orion_version }}'