- name: Criar diret贸rios
  become: yes
  hosts: "{{ host_awx }}"
  gather_facts: no
  tasks:
    - name: Criar diret贸rios usando o m贸dulo file
      file:
        path: /var/volumes
        state: directory
      ignore_errors: yes

    - name: Criar diret贸rios dentro de /var/volumes
      file:
        path: "/var/volumes/{{ item }}"
        state: directory
      loop:
        - backend/logs
        - rabbitmq/logs
        - bd/logs
        - frontend/conf.d
        - gateway/includes
        - gateway/logs
        - worker/logs
        - gateway/logs/cdr-csv
        - gateway/logs/cdr-custom
        - loadbalancer/includes
        - voice/logs
        - voice/logs/cdr-csv
        - voice/logs/cdr-custom
      ignore_errors: yes

