---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Escrever mensagem no log
      command: echo "\033[32m####_INICIANDO_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt
      async: 300
      poll: 0
      register: log_result
    - name: Acessar path files
      shell: cd /home/awx/orion/infra/servicos/files
      
    - name: Criar imagem Docker 'files'
      shell: docker buildx build --no-cache --progress plain --platform '${ORION_ARCH}' -t '${ORION_REGISTRY}/files:${ORION_ARCH}-latest' .
      ignore_errors: yes

    - name: Executar 'docker images' para listar imagens com 'files'
      command: docker images --filter "reference=*files*" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      async: 300
      poll: 0
      register: docker_images_result



      



