---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:

    - name: publish www
      shell: dotnet publish --no-self-contained -r linux-musl-x64 --configuration Release -o www /home/awx/orion/backend/Orion/
