---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Executar install nvm
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install 16.13.1 >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: nvm_install_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_INSTALL_ANGULAR####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar install angular
      shell: npm update npm -g && npm install -g @angular/cli@13.* >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: angular_install_result
    
    
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_INSTALL_IONIC####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar install angular
      shell: npm install -g @ionic/cli@6.*  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: ionic_install_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_INSTALL_NPM####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar install angular
      shell: npm install >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: npm_install_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_BUILD_FRONT####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Escrever mensagem no log
      shell: cd /home/awx/fronted/ && ng build --configuration {{ front_version }} --output-path www >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: build_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_BUILD_IMAGEM_FRONT####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Escrever mensagem no log
      shell: docker build -t {{ ORION_REGISTRY }}/frontend:{{ ORION_ARCH }}-latest /home/awx/fronted/www/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_build_result
