---
- name: Clonar Repositório do GitLab
  hosts: 192.168.18.41
  gather_facts: no
  tasks:
    - name: Clonar o repositório
      git:
        repo: "https://{{ gitlab_user }}:{{pass_gitlab}}@gitlab.com/dbm-orion/backend.git"
        dest: /home/awx/orion/
        clone: yes
        version: "dev2"
      become: no
      environment:
        GIT_SSL_NO_VERIFY: "1"