---
- name: Clonar repositório backendGitLab 
  hosts: all
  gather_facts: no
  tasks:
    - name: Clonar repositório backend
      git:
        repo: https://gitlab.com/dbm-orion/backend.git
        dest: /home/awx/orion
        version: dev2
      environment:
        GIT_ASKPASS: diogoscrobut:Cox@2016