---
- name: Clonar Repositório do GitLab
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clonar o repositório
      git:
        repo: "https://gitlab.com/dbm-orion/backend.git"
        dest: "/caminho/para/destino"
        clone: yes
      become: no
      environment:
        GIT_SSL_NO_VERIFY: "1"