---
- name: Clonar Repositório do GitLab
  hosts: all
  gather_facts: no
  tasks:
    - name: Clonar o repositório
      git:
        repo: "https://github.com/scrobut/firstAppFlutter.git"
        dest: /home/awx/orion/
        clone: yes
      become: no
      environment:
        GIT_SSL_NO_VERIFY: "1"