---
- name: Clonar Repositório do GitLab
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clonar o repositório
      git:
        repo: "https://{{ gitlab_token }}@gitlab.com/dbm-orion/backend.git"
        dest: /home/awx/
        clone: yes
      become: no
      environment:
        GIT_SSL_NO_VERIFY: "1"
        GIT_ASKPASS: "{{ pass_gitlab }}"