---
- name: Clonar Repositório do GitLab
  hosts: "{{ host_awx }}"
  gather_facts: no
  tasks:
    - name: Clonar o repositório
      git:
        repo: "https://{{ gitlab_user }}:{{pass_gitlab}}@gitlab.com/dbm-orion/backend.git"
        dest: /home/awx/orion/backend
        clone: yes
        version: "{{ version_backend }}"
      become: no
      environment:
        GIT_SSL_NO_VERIFY: "1"