---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Log Message - Iniciando deploy
      command: echo "\033[32m####_ADICIONANDO_USUARIO_AO_GRUPO_DOCKER####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt

    - name: Adiciona o usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Espera 1 segundo
      pause:
        seconds: 1

    - name: Log Message - Iniciando update
      command: echo "\033[32m####_INICIANDO_UPDATE####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt

    - name: Executa o comando apt-get update
      command: apt-get update -y > /var/log/ansible_deploy_logs/deploy_log.txt
      async: 600
      poll: 0
      register: update_result

    - name: Espera 3 segundos
      pause:
        seconds: 3

    - name: Log Message - Iniciando instalação do .NET
      command: echo "\033[32m####_INICIANDO_INSTALAÇÃO_DOTNET####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt

    - name: Instale o apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Atualize a lista de pacotes novamente
      apt:
        update_cache: yes

    - name: Instale o pacote dotnet-sdk-6.0
      apt:
        name: dotnet-sdk-6.0
        state: present

    - name: Log Message - Versão do .NET
      command: echo "\033[32m####_VERSAO_DOTNET_####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt

    - name: Exibe a versão do .NET
      command: dotnet --version >> /var/log/ansible_deploy_logs/deploy_log.txt
