---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Criar diretório de logs
      file:
        path: "/var/log/ansible_deploy_logs"
        state: directory
      when: not ansible_check_mode

    - name: Executa o comando apt-get update
      command: apt-get update > /var/log/ansible_deploy_logs/apt_update.log 2>&1
      args:
        warn: no
      async: 600
      poll: 0
      register: update_result

    - name: Instala pacotes adicionais
      command: apt install -y apache2-utils apt-transport-https bash-completion ca-certificates curl gnupg software-properties-common tcpdump wget ufw net-tools tree vim > /var/log/ansible_deploy_logs/pacotes_adicionais.log 2>&1
      args:
        warn: no
      async: 600
      poll: 0
      register: install_result

    - name: Instalando Docker
      command: apt install -y docker.io > /var/log/ansible_deploy_logs/docker_install.log 2>&1
      args:
        warn: no
      async: 600
      poll: 0
      register: docker_install_result

    - name: Adiciona o usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Instala o .NET SDK 6.0
      block:
        - name: Baixa o pacote de configuração do repositório do Microsoft
          get_url:
            url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
            dest: ~/packages-microsoft-prod.deb
          become: yes

        - name: Instala o pacote de configuração do repositório do Microsoft
          command: dpkg -i ~/packages-microsoft-prod.deb
          become: yes

        - name: Executa apt-get update (SDK)
          command: apt-get update > /var/log/ansible_deploy_logs/dotnet_sdk_update.log 2>&1
          args:
            warn: no
          async: 600
          poll: 0
          register: dotnet_sdk_update_result

        - name: Instala o pacote apt-transport-https
          apt:
            name: apt-transport-https
            state: present
          become: yes

        - name: Executa apt-get update (SDK - segunda vez)
          command: apt-get update > /var/log/ansible_deploy_logs/dotnet_sdk_second_update.log 2>&1
          args:
            warn: no
          async: 600
          poll: 0
          register: dotnet_sdk_second_update_result

        - name: Instala o pacote dotnet-sdk-6
          command: apt install -y dotnet-sdk-6.0 > /var/log/ansible_deploy_logs/dotnet_sdk_install.log 2>&1
          args:
            warn: no
          async: 600
          poll: 0
          register: dotnet_sdk_install_result

      when: not ansible_check_mode

    - name: Log do resultado das ações
      copy:
        content: |
          Execução do apt-get update:
          {{ lookup('file', '/var/log/ansible_deploy_logs/apt_update.log') | default("Nenhum resultado", true) }}

          Instalação de pacotes adicionais:
          {{ lookup('file', '/var/log/ansible_deploy_logs/pacotes_adicionais.log') | default("Nenhum resultado", true) }}

          Instalação do Docker:
          {{ lookup('file', '/var/log/ansible_deploy_logs/docker_install.log') | default("Nenhum resultado", true) }}

          Instalação do .NET SDK 6.0 (Update):
          {{ lookup('file', '/var/log/ansible_deploy_logs/dotnet_sdk_update.log') | default("Nenhum resultado", true) }}

          Instalação do .NET SDK 6.0 (Update - segunda vez):
          {{ lookup('file', '/var/log/ansible_deploy_logs/dotnet_sdk_second_update.log') | default("Nenhum resultado", true) }}

          Instalação do .NET SDK 6.0:
          {{ lookup('file', '/var/log/ansible_deploy_logs/dotnet_sdk_install.log') | default("Nenhum resultado", true) }}
        dest: "/var/log/ansible_deploy_logs/deploy_log.txt"
      when: update_result.changed or install_result.changed or docker_install_result.changed or dotnet_sdk_update_result.changed or dotnet_sdk_second_update_result.changed or dotnet_sdk_install_result.changed
    