---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Criar diretório de logs
      file:
        path: "/var/log/ansible_deploy_logs"
        state: directory
      when: not ansible_check_mode

    - name: Executa o comando apt-get update
      shell: apt-get update
      args:
        warn: no
      register: update_result
      ignore_errors: yes

    - name: Exibe resultado do apt-get update
      debug:
        var: update_result.stdout_lines

    - name: Instala pacotes adicionais
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2-utils
        - apt-transport-https
        - bash-completion
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - tcpdump
        - wget
        - ufw
        - net-tools
        - tree
        - vim
      register: install_result
      ignore_errors: yes

    - name: Exibe resultado da instalação de pacotes adicionais
      debug:
        var: install_result.stdout_lines

    - name: Instalando Docker
      apt:
        name: docker.io
        state: present
      register: docker_install_result
      ignore_errors: yes

    - name: Exibe resultado da instalação do Docker
      debug:
        var: docker_install_result.stdout_lines

    - name: Adiciona o usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Log do resultado das ações
      copy:
        content: |
          Execução do apt-get update:
          {{ update_result.stdout_lines | join('\n') }}
          
          Instalação de pacotes adicionais:
          {{ install_result.stdout_lines | join('\n') }}
          
          Instalação do Docker:
          {{ docker_install_result.stdout_lines | join('\n') }}
        dest: "/var/log/ansible_deploy_logs/deploy_log.txt"
      when: update_result.changed or install_result.changed or docker_install_result.changed
