---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Criar diretório de logs
      file:
        path: "/var/log/ansible_deploy_logs"
        state: directory
      when: not ansible_check_mode # Cria o diretório apenas em execuções reais

    - name: Executa o comando apt-get update
      apt:
        update_cache: yes
      register: update_result
      ignore_errors: yes
      changed_when: update_result.changed

    - name: Exibe resultado da atualização
      debug:
        var: update_result

    - name: Log do resultado da atualização 
      copy:
        content: "{{ update_result.stdout | default('No output') }}"
        dest: "/var/log/ansible_deploy_logs/update_result.log"
      when: update_result.changed
