---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Criar diretório de logs
      file:
        path: "/var/log/ansible_deploy_logs"
        state: directory
      when: not ansible_check_mode

    - name: Executa o comando apt-get update
      shell: apt-get update
      args:
        warn: no
      register: update_result

    - name: Instala pacotes adicionais
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2-utils
        - apt-transport-https
        - bash-completion
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - tcpdump
        - wget
        - ufw
        - net-tools
        - tree
        - vim
      register: install_result
      ignore_errors: yes

    - name: Instalando Docker
      apt:
        name: docker.io
        state: present
      register: docker_install_result
      ignore_errors: yes

    - name: Adiciona o usuário ao grupo Docker
      shell: sudo usermod -aG docker $USER
      args:
        warn: no
      register: add_user_to_docker_result
      ignore_errors: yes

    - name: Log do resultado das ações
      copy:
        content: |
          Execução do apt-get update:
          {{ update_result.stdout | default("Nenhum resultado", true) }}
          
          Instalação de pacotes adicionais:
          {{ install_result.stdout | default("Nenhum resultado", true) }}
          
          Instalação do Docker:
          {{ docker_install_result.stdout | default("Nenhum resultado", true) }}
          
          Adição do usuário ao grupo Docker:
          {{ add_user_to_docker_result.stdout | default("Nenhum resultado", true) }}
        dest: "/var/log/ansible_deploy_logs/deploy_log.txt"
      when: update_result.changed or install_result.changed or docker_install_result.changed or add_user_to_docker_result.changed
