---
- name: Inicia Deploy Gateway
  hosts: "{{ host_voice }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Log Message Iniciando deploy  # Registra uma mensagem indicando a adição do usuário ao grupo Docker
      shell: echo "\033[32m####_ADICIONANDO_USUARIO_AO_GRUPO_DOCKER####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Adiciona o usuário ao grupo Docker  # Adiciona o usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Espera 1 segundo  # Pausa por 1 segundo
      pause:
        seconds: 1
    
    # Registra uma mensagem indicando o update
    - name: Log Message Iniciando update de pacotes 
      shell: echo "\033[32m####_UPDATE_PACOTES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
    - name: Executa o comando apt-get update
      command: apt-get update -y > /var/log/ansible_deploy_logs/deploy_log.txt
      async: 600
      poll: 0
      register: update_result
