---
- name: Inicia Deploy Gateway
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: yes
  tasks:
    - name: Criar diretório de logs
      file:
        path: "/var/log/ansible_deploy_logs"
        state: directory
        owner: awx
        group: awx
        mode: 0755
      when: not ansible_check_mode

    - name: Criar arquivo de log
      file:
        path: "/var/log/ansible_deploy_logs/deploy_log.txt"
        state: touch
        owner: awx
        group: awx
        mode: 0644
      when: not ansible_check_mode

    - name: Executa o comando apt-get update
      shell: apt-get update > /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      async: 600
      poll: 0
      register: update_result

    - name: Instala pacotes adicionais
      shell: apt install -y apache2-utils apt-transport-https bash-completion ca-certificates curl gnupg software-properties-common tcpdump wget ufw net-tools tree vim > /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      async: 600
      poll: 0
      register: install_result

    - name: Instalando Docker
      shell: apt install -y docker.io >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      async: 600
      poll: 0
      register: docker_install_result

    - name: Adiciona o usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes

    - name: Instala o .NET SDK 6.0
      block:
        - name: Baixa o pacote de configuração do repositório do Microsoft
          get_url:
            url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
            dest: ~/packages-microsoft-prod.deb
          become: yes

        - name: Instala o pacote de configuração do repositório do Microsoft
          command: sudo dpkg -i ~/packages-microsoft-prod.deb

        - name: Executa apt-get update (SDK)
          shell: apt-get update >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
          async: 600
          poll: 0
          register: dotnet_sdk_update_result

        - name: Instala o pacote apt-transport-https
          apt:
            name: apt-transport-https
            state: present
          become: yes

        - name: Executa apt-get update (SDK - segunda vez)
          shell: apt-get update >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
          async: 600
          poll: 0
          register: dotnet_sdk_second_update_result

        - name: Instala o pacote dotnet-sdk-6
          shell: apt install -y dotnet-sdk-6.0 >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
          async: 600
          poll: 0
          register: dotnet_sdk_install_result

      when: not ansible_check_mode
