---
- name: Inicia Deploy Gateway e Configuracao Docker Swarm
  hosts: "{{ host_awx }}"
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: Inicializar Docker Swarm
      command: docker swarm init
      register: swarm_init_output
      ignore_errors: true  # Ignorar erros se o Swarm já estiver inicializado

    - name: Verificar se o Swarm foi inicializado
      assert:
        that: "'Swarm initialized' in swarm_init_output.stdout"

    - name: Extrair o comando de junção do Swarm
      set_fact:
        swarm_join_command: "{{ swarm_init_output.stdout | regex_search('docker swarm join --token [^ ]+ [0-9:.]+') }}"

- name: Acessar Nó para Ingressar no Swarm
  hosts: "{{ host_voice }}"
  become: yes
  tasks:
    - name: Ingressar no Docker Swarm como manager
      command: "{{ swarm_join_command }}"

- name: Verificar Status do Nó no Swarm
  hosts: "{{ host_awx }}"
  become: yes
  tasks:
    - name: Executar 'docker node ls'
      command: docker node ls
