---
- name: Inicia Deploy Gateway e Configuracao Docker Swarm
  hosts: "{{ host_awx }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Inicializar Docker Swarm
      command: docker swarm init
      register: swarm_init_output

    - set_fact:
        swarm_join_token_task: "{{ swarm_init_output.stdout_lines | select('match', '^docker swarm join') | list | first }}"
      when: swarm_init_output.stdout_lines | search('^Swarm initialized')

    - name: Debug - Mostrar o valor de swarm_join_token_task
      debug:
        var: swarm_join_token_task

- name: Acessar Nó para Ingressar no Swarm
  hosts: "{{ host_voice }}"
  become: yes
  tasks:
    - name: Ingressar no Docker Swarm como manager
      command: "{{ swarm_join_token_task }}"
      when: swarm_join_token_task is defined

- name: Verificar Status do Nó no Swarm
  hosts: "{{ host_awx }}"
  become: yes
  tasks:
    - name: Executar 'docker node ls'
      command: docker node ls
