---
- name: Inicia Deploy Gateway e Configuracao Docker Swarm
  hosts: "{{ host_awx }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Inicializar Docker Swarm
      command: docker swarm init
      register: swarm_init_output

    - name: Verificar se o Swarm foi inicializado
      assert:
        that: "'Swarm initialized' in swarm_init_output.stdout"
      register: swarm_initialized
      changed_when: false

    - name: Extrair o comando de junção do Swarm
      set_fact:
        swarm_join_command: "{{ swarm_init_output.stdout_lines | join('\n') }}"
      when: swarm_initialized.failed == false

    - name: Debug - Mostrar o valor de swarm_join_command
      debug:
        var: swarm_join_command

- name: Acessar Nó para Ingressar no Swarm
  hosts: "{{ host_voice }}"
  become: yes
  tasks:
    - name: Ingressar no Docker Swarm como manager
      command: "{{ swarm_join_command }}"
      when: swarm_join_command is defined

- name: Verificar Status do Nó no Swarm
  hosts: "{{ host_awx }}"
  become: yes
  tasks:
    - name: Executar 'docker node ls'
      command: docker node ls
