---
- name: Inicia Deploy Gateway e Configuracao Docker Swarm
  hosts: "{{ host_awx }}"
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    swarm_join_command: null  # Defina a variável como nula no início

  tasks:
    - name: Inicializar Docker Swarm
      command: docker swarm init
      register: swarm_init_output

    - name: Verificar se o Swarm foi inicializado
      assert:
        that: "'Swarm initialized' in swarm_init_output.stdout"

    - name: Extrair o comando de junção do Swarm
      set_fact:
        swarm_join_command: "{{ swarm_init_output.stdout | regex_search('docker swarm join --token [^ ]+ [0-9:.]+') }}"
      when: swarm_init_output.stdout is defined

- name: Acessar Nó para Ingressar no Swarm
  hosts: "{{ host_voice }}"
  become: yes
  
- name: Debug swarm_join_command
  hosts: "{{ host_voice }}"
  gather_facts: no
  tasks:
    - name: Debug swarm_join_command
      debug:
        var: swarm_join_command


- name: Verificar Status do Nó no Swarm
  hosts: "{{ host_awx }}"
  become: yes
  tasks:
    - name: Executar 'docker node ls'
      command: docker node ls
