---
- name: Inicia Deploy Gateway e Configuracao Docker Swarm
  hosts: "{{ host_awx }}"
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Inicializar Docker Swarm
      command: docker swarm init
      register: swarm_init_output

    - name: Verificar se o Swarm foi inicializado
      assert:
        that: "'Swarm initialized' in swarm_init_output.stdout"
      register: swarm_initialized
      changed_when: false

    - name: Extrair o token de junção
      set_fact:
        swarm_join_token_task: "{{ swarm_init_output.stdout_lines | regex_search('(SWMTKN-[^ ]+)') }}"
      when: swarm_initialized.failed == false

    - name: Debug - Mostrar o valor de swarm_join_token_task
      debug:
        var: swarm_join_token_task

- name: Acessar Nó para Ingressar no Swarm
  hosts: "{{ host_voice }}"
  become: yes
  tasks:
    - name: Ingressar no Docker Swarm como manager
      command: "docker swarm join --token {{ swarm_join_token_task }} 192.168.18.47:2377"
      when: swarm_join_token_task is defined

- name: Verificar Status do Nó no Swarm
  hosts: "{{ host_awx }}"
  become: yes
  tasks:
    - name: Executar 'docker node ls'
      command: docker node ls
