---
- name: Criar diretórios e definir permissões
  hosts: "{{ host_awx }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/files:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/files/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_FILES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/files  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_POSTGRES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/postgres:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/postgres/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_POSTGRES####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/postgres  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_ASTERISK####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/asterisk:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/asterisk/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_ASTERISK####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/asterisk  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_GATEWAY####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/gateway:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/gateway/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_GATEWAY####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/gateway  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result


    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_ARQUIVO_DUNDI_PERERS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Capturar endereço MAC
      shell: ifconfig enp0s3 | awk '/ether/{print $2}'
      register: mac_result

    - name: Criar arquivo
      file:
        path: /var/volumes/gateway/includes/dundi_peers.conf
        state: touch

    # Adiciona o texto ao arquivo, incluindo o endereço MAC capturado
    - name: Adicionar texto
      lineinfile:
        path: /var/volumes/gateway/includes/dundi_peers.conf
        line: |
          [{{ mac_result.stdout }}];
          model = symmetric
          precache = none
          host = {{ host_voice }};
          port = 4520
          inkey = dundi
          outkey = dundi
          include = dundi_context
          permit = dundi_context
          qualify = 6500
          register = no

    - name: Capturar dados do arquivo dundi
      shell: cat /var/volumes/gateway/includes/dundi_peers.conf >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: mac_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_ARQUIVO_UPSTREAM####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Criar arquivo
      file:
        path: /var/volumes/loadbalancer/includes/upstream.conf
        state: touch

    # Adiciona o texto ao arquivo upstream
    - name: Adicionar texto
      lineinfile:
        path: /var/volumes/loadbalancer/includes/upstream.conf
        line: |
          upstream voice_nodes {
          # Voice 1
          server {{ host_voice }} max_fails=2 fail_timeout=5s;
          }

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_LOADBALANCER####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/loadbalancer:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/loadbalancer/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_BALANCER####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/loadbalancer  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result


    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_VOICE####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build --no-cache --force-rm -t {{ ORION_REGISTRY }}/voice:{{ ORION_ARCH }}-latest /home/awx/orion/infra/servicos/voice/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_VOICE####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images --filter reference=dbmorion/voice >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result  

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_PUBLISH_BACKEND_WWW####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: publish www
      shell: cd /home/awx/orion/backend/Orion/ && dotnet publish --no-self-contained -r linux-musl-x64 --configuration Release -o www >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_BACKEND####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar script Docker Buildx
      shell: docker build -t {{ ORION_REGISTRY }}/backend:{{ ORION_ARCH }}-latest --build-arg ENVIRONMENT={{ orion_version }}  /home/awx/orion/backend/Orion/www/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_IMAGEM_BACKEND####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'backend'
      shell: docker images --filter reference=dbmorion/backend  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_LISTA_TODAS_IMAGENS####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Executar 'docker images' para listar imagens com 'files'
      shell: docker images  >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_images_result
      
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_DOWNLOAD_NVM####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_IMAGEM_FRONTEND####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result
      
    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_BUILD_FRONT####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Escrever mensagem no log
      shell: cd /home/awx/frontend2/ && ng build --configuration {{ front_version }} --output-path www >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: build_result

    - name: Escrever mensagem no log
      shell: echo "\033[32m####_INICIANDO_BUILD_IMAGEM_FRONT####\033[0m" >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: log_result

    - name: Escrever mensagem no log
      shell: docker build -t {{ ORION_REGISTRY }}/frontend:{{ ORION_ARCH }}-latest /home/awx/fronted/www/ >> /var/log/ansible_deploy_logs/deploy_log.txt 2>&1
      register: docker_build_result
